name: Deploy to o2switch
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer et Construire
        run: |
          npm ci
          npm run build

      # ÉTAPE 1 : ENVOI DU SITE
      - name: Envoyer le site (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: l-atelier-archi/dist/
          local-dir: ./dist/

      # ÉTAPE 2 : REDÉMARRAGE
      - name: Préparer le redémarrage
        run: |
          mkdir -p restart-trigger
          date > restart-trigger/restart.txt

      - name: Déclencher le redémarrage (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: l-atelier-archi/tmp/
          local-dir: ./restart-trigger/